spring:
  datasource:
    name: mydev 
    url: jdbc:mysql://120.55.171.108:3306/opensource-dev?useUnicode=true&characterEncoding=utf-8
    username: opensource
    password: opensource
    driver-class-name: com.mysql.jdbc.Driver
    dbcp:
      min-idle: 3
      max-active: 10
      initial-size: 5
      time-between-eviction-runs-millis: 3000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'ZTM' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  redis:
    host: 120.55.171.108
    port: 6379
    database: 0
    password: opensource
    pool:
      max-active: 1024
      max-idle: 200
      max-wait: 1000
      min-idle: 50
    timeout: 60
    test-on-borrow: true
    max-total: 1024
    max-wait-millis: 1000
    time-between-eviction-runs-millis: 60
    
server:
  port: 18080