spring:
  profiles:
    active:
      - dev
server:
  port: 18080
---
spring:
  profiles:
    active:
      - qa
server:
  port: 28080
---

spring:
  profiles:
    active:
      - ali
server:
  port: 38080
---

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  
mybatis:
  mapper-locations: classpath*:com/chinaopensource/apiserver/**/mapper/*Mapper.xml
  