spring:
  datasource:
    name: myali
    url: jdbc:mysql://localhost:3306/opensource-ali
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    dbcp:
      min-idle: 3
      max-active: 10
      initial-size: 5
      time-between-eviction-runs-millis: 3000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'ZTM' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  redis:
    host: localhost
    port: 6379
    database: 1
    password: opensource
    pool:
      max-active: 1024
      max-idle: 200
      max-wait: 1000
      min-idle: 50
    timeout: 60
    test-on-borrow: true
    max-total: 1024
    max-wait-millis: 1000
    time-between-eviction-runs-millis: 60
    
server:
  port: 38080