spring:
  profiles:
    active:
      - dev
    
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  
mybatis:
  mapper-locations: classpath*:com/chinaopensource/apiserver/**/mapper/*Mapper.xml
  