spring:
  profiles:
    active: dev
  
mybatis:
  mapper-locations: classpath*:com/chinaopensource/apiserver/**/mapper/*Mapper.xml
  type-aliases-package: com.chinaopensource.apiserver
  configuration:
    mapUnderscoreToCamelCase: true
  
pagehelper:
  helper-dialect: mysql
