spring:
  datasource:
    name: myali
    url: jdbc:mysql://39.106.101.36:3306/opensource-ali?useUnicode=true&characterEncoding=utf-8
    username: opensource
    password: opensource
    driver-class-name: com.mysql.jdbc.Driver
    dbcp:
      min-idle: 3
      max-active: 10
      initial-size: 5
      time-between-eviction-runs-millis: 3000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'ZTM' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  redis:
    host: localhost
    port: 6379
    database: 1
    password: opensource
    pool:
      max-active: 1024
      max-idle: 200
      max-wait: 1000
      min-idle: 50
    timeout: 60
    test-on-borrow: true
    max-total: 1024
    max-wait-millis: 1000
    time-between-eviction-runs-millis: 60
    
server:
  port: 9080

opensource:
  jwt:
    header: Authorization
    secret: mySecret
    expiration: 1800
  image:
    width: 120
    height: 30
  host:
    ip: 39.106.101.36
  email:
    auth: 907678041@qq.com
    passwd: lzl1593572798
    smtp-host-key: mail.smtp.host
    smtp-host-value: mx1.qq.com
    smtp-protocol-key: mail.store.protocol
    smtp-protocol-value: smtp
    smtp-port-key: mail.smtp.port
    smtp-port-value: 25
    smtp-auth-key: mail.smtp.auth
    smtp-auth-value: true
    encode-pattern: gb2312
    content-pattern: text/html;charset=gb2312